import React, { useEffect, useState } from "react";
import {
  Box,
  Flex,
  Button,
  Table,
  Thead,
  Tbody,
  Tr,
  IconButton,
  Th,
  Td,
  TableContainer,
  Spinner,
  Badge,
  Tooltip,
} from "@chakra-ui/react";
import { ArrowBackIcon } from "@chakra-ui/icons";

import Header from "../../Components/Pages/Header";
import Footer from "../../Components/Pages/Footer";
import HeadingButtonSection from "../../Components/Pages/HeadingButtonSection";
import axios from "axios";
import { useNavigate, useParams } from "react-router-dom";

const TeacherResults = () => {
  const [resultData, setResultData] = useState([]);
  const { course_id, assignment_id, student_id } = useParams();

  console.log(resultData);

  const [loading, setLoading] = useState(true);
  const fetchData = async () => {
    try {
      const token = localStorage.getItem("accessToken");
      const config = { headers: { Authorization: `Bearer ${token}` } };

      const response = await axios.get(
        `https://smartassess-backend-t3l93.ondigitalocean.app/teacher/course/${course_id}/assignment/${assignment_id}/student/${student_id}/evaluation`,
        config
      );

      if (response.status === 200) {
        setResultData(response.data.result);
      }
    } catch (err) {
      console.error("Error fetching student data:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const [expandedIndex, setExpandedIndex] = useState(null);

  const toggleExpand = (index) => {
    setExpandedIndex(expandedIndex === index ? null : index);
  };

  const nav = useNavigate();

  return (
    <Flex direction="column" minH="100vh">
      <Header />
      <Box flex="1" mx={12} overflowY="auto" paddingBottom="80px">
        <Flex
          flexWrap={"wrap"}
          alignItems={"center"}
          justifyContent={"space-between"}
        >
          <IconButton
            aria-label="Go Back"
            icon={<ArrowBackIcon />}
            onClick={() =>
              nav(`/teacher/student/grading/${course_id}/${assignment_id}`)
            }
            mr={4}
          />
          <Box>
            <HeadingButtonSection
              path="Results"
              content="Marketing"
              showButton={false}
              showBulkAddButton={false}
            />
          </Box>
        </Flex>

        <Flex mb={6} gap={6} justifyContent={"space-between"} flexWrap={"wrap"}>
          <Box flexWrap={"wrap"} display={"flex"} alignItems={"center"} gap={2}>
            {[
              {
                label: `Total Score ${resultData.total_score}/${resultData.total_assignment_grade}`,
                tooltip:
                  "This represents your total score achieved out of the maximum possible.",
              },
              {
                label: `Avg AI Detection ${(resultData?.ai_score * 100).toFixed(
                  2
                )}%`,
                tooltip:
                  "This score indicates the likelihood that content was generated by AI tools like ChatGPT. If AI detection score is greater than 90%, the total score will be zero for that question.",
              },
              {
                label: `Avg Grammar Detection ${(
                  resultData?.grammar_score * 100
                ).toFixed(2)}%`,
                tooltip:
                  "This score reflects how grammatically accurate your submission is.",
              },
              {
                label: `Avg Plagiarism Detection ${(
                  resultData?.plagiarism_score * 100
                ).toFixed(2)}%`,
                tooltip:
                  "This score shows the similarity of your content with existing sources.If plagirism score is greater than 90% then total score will be zero of that question",
              },
              {
                label: `Overall Feedback`,
                tooltip:
                  resultData?.feedback ||
                  "Instructor's feedback based on your performance.",
              },
            ].map((item, idx) => (
              <Tooltip key={idx} label={item.tooltip} hasArrow>
                <Badge color="white" bg="blue.500" cursor="pointer">
                  {item.label}
                </Badge>
              </Tooltip>
            ))}
          </Box>
          <Box>
            <Button
              colorScheme="blue"
              onClick={() => {
                const link = document.createElement("a");
                link.href = resultData?.report_url; // Use report_url here
                link.download = "Report.pdf";
                link.click();
              }}
            >
              Download Report
            </Button>
          </Box>
        </Flex>

        <TableContainer
          mb={12}
          height="100%"
          width={"100%"}
          border="1px solid #e0e0e0"
          boxShadow="lg"
          borderRadius="xl"
        >
          {loading ? (
            <Flex height="300px" justifyContent="center" alignItems="center">
              <Spinner
                size="lg"
                thickness="4px"
                speed="0.65s"
                color="blue.500"
              />
            </Flex>
          ) : (
            <>
              <Table variant="simple">
                <Thead backgroundColor={"#EAEEF0"}>
                  <Tr>
                    <Th>Question</Th>
                    <Th>Student Answer</Th>
                    <Th>Question Score</Th>
                    <Th>Context Score</Th>
                    <Th>Grammar Score</Th>
                    <Th>Plagirism Score</Th>
                    <Th>AI Detection</Th>
                    <Th>Feedback</Th>
                  </Tr>
                </Thead>
                <Tbody>
                  {resultData?.questions?.map((assignment, index) => (
                    <Tr key={index}>
                      <Td
                        onClick={() => toggleExpand(index)}
                        maxW="300px"
                        overflow="hidden"
                        whiteSpace={
                          expandedIndex === index ? "normal" : "nowrap"
                        }
                        textOverflow="ellipsis"
                        cursor="pointer"
                        title={assignment.question_text}
                      >
                        Q#
                        {assignment.question_number} {assignment.question_text}
                      </Td>

                      <Td
                        onClick={() => toggleExpand(index)}
                        maxW="300px"
                        overflow="hidden"
                        whiteSpace={
                          expandedIndex === index ? "normal" : "nowrap"
                        }
                        textOverflow="ellipsis"
                        cursor="pointer"
                        title={assignment.student_answer}
                      >
                        {assignment.student_answer}
                      </Td>

                      <Td>
                        {assignment?.question_score != null
                          ? assignment.question_score.toFixed(2)
                          : "0.00"}
                        /{resultData?.question_total_marks}
                      </Td>
                      <Td>{(assignment.context_score * 100).toFixed(2)}%</Td>
                      <Td>{(assignment.grammar_score * 100).toFixed(2)}%</Td>
                      <Td>{(assignment.plagiarism_score * 100).toFixed(2)}%</Td>
                      <Td>{(assignment.ai_score * 100).toFixed(2)}%</Td>

                      <Td>
                        <Box
                          maxW="200px"
                          cursor="pointer"
                          overflow="hidden"
                          textOverflow="ellipsis"
                          whiteSpace={assignment.showFull ? "normal" : "nowrap"}
                          onClick={() =>
                            setResultData((prev) => ({
                              ...prev,
                              questions: prev.questions.map((q, i) =>
                                i === index
                                  ? { ...q, showFull: !q.showFull }
                                  : q
                              ),
                            }))
                          }
                        >
                          {assignment.feedback}
                        </Box>
                      </Td>
                    </Tr>
                  ))}
                </Tbody>
              </Table>
              <Flex px={6} py={2} pb={6} justifyContent={"space-between"}>
                <Button mt={4} onClick={() => alert("Previous Page")} mr={2}>
                  Previous
                </Button>
                <Button mt={4} onClick={() => alert("Next Page")}>
                  Next
                </Button>
              </Flex>
            </>
          )}
        </TableContainer>
      </Box>
      <Footer />
    </Flex>
  );
};

export default TeacherResults;
